# Site settings
production: true
title: In Lehman's Terms
description: ""
timezone: America/New_York
usernames:
  disqus: inlehmansterms
  twitter: inLehmans_Terms
  github: jdlehman

# Build settings
markdown: redcarpet
redcarpet:
  extensions:
    - fenced_code_blocks
    - autolink
    - strikethrough
    - lax_spacing
    - superscript
    - with_toc_data
permalink: pretty
highlighter: rouge

# Gem Settings
gems:
  - jekyll-assets
  - jekyll-sitemap

# Jekyll-assets settings
assets:
  js_compressor:  uglifier
  css_compressor: sass
  cache: true
  cachebust: hard
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts

# Files to exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - bower_components
  - bower.json
  - Rakefile
