# Site settings
title: In Lehman's Terms
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://localhost:4000"
timezone: America/New_York
usernames:
  disqus: jdlehman

# Build settings
markdown: redcarpet
redcarpet:
    extensions:
      - fenced_code_blocks
      - autolink
      - strikethrough
      - lax_spacing
      - superscript
      - with_toc_data
permalink: pretty
highlighter: rouge

# Gem Settings
gems:
  - jekyll-assets

# Jekyll-assets settings
assets:
  js_compressor:  uglifier
  css_compressor: sass
  cache: true

# Files to exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - bower_components
  - bower.json
