# Site settings
title: In Lehman's Terms
description: ""
timezone: America/New_York
usernames:
  disqus: jdlehman

# Build settings
markdown: redcarpet
redcarpet:
  extensions:
    - fenced_code_blocks
    - autolink
    - strikethrough
    - lax_spacing
    - superscript
    - with_toc_data
permalink: pretty
highlighter: rouge

# Gem Settings
gems:
  - jekyll-assets

# Jekyll-assets settings
assets:
  js_compressor:  uglifier
  css_compressor: sass
  cache: true

# Files to exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - bower_components
  - bower.json
