# Site settings
production: true
baseurl: /in_lehmans_terms
title: In Lehman's Terms
description: ""
timezone: America/New_York
usernames:
  disqus: inlehmansterms
  twitter: inLehmans_Terms
  github: jdlehman

# Build settings
markdown: redcarpet
redcarpet:
  extensions:
    - fenced_code_blocks
    - autolink
    - strikethrough
    - lax_spacing
    - superscript
    - with_toc_data
permalink: pretty
highlighter: rouge

# Gem Settings
gems:
  - jekyll-assets

# Jekyll-assets settings
assets:
  js_compressor:  uglifier
  css_compressor: sass
  cache: true
  cachebust: hard
  baseurl: /in_lehmans_terms/assets/

# Files to exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - bower_components
  - bower.json
  - Rakefile

# Rakefile config
post:
  template: _post_template.txt
  extension: md
page:
  template: _page_template.txt
  extension: md
editor: vim
